export const PLANNER_PLAN_READ_PROJECTION = [
  'userId',
  'platform',
  'weekStart',
  'userTimeZone',
  'slots.slotId',
  'slots.dayOfWeek',
  'slots.blockStartHour',
  'slots.format',
  'slots.categories',
  'slots.status',
  'slots.isExperiment',
  'slots.expectedMetrics',
  'slots.recordingTimeSec',
  'slots.aiVersionId',
  'slots.title',
  'slots.scriptShort',
  'slots.notes',
  'slots.themeKeyword',
].join(' ');
