import type { PlannerUISlot, TimeBlockScoreUI } from "@/hooks/usePlannerData";

export const PREVIEW_PLANNER_SLOTS: PlannerUISlot[] = [
  {
    slotId: "preview-slot-seg-9",
    dayOfWeek: 1,
    blockStartHour: 9,
    format: "reel",
    categories: {
      context: ["creator_routine"],
      tone: "confiante",
      proposal: ["bastidores"],
    },
    status: "planned",
    expectedMetrics: { viewsP50: 12400, viewsP90: 28600, sharesP50: 210 },
    title: "3 sinais de que sua rotina de creator está travando consistência",
    scriptShort: "Hook com dor real, bastidor curto do processo e fechamento com ajuste simples para a semana.",
    themes: ["rotina de creator", "consistência", "bastidores de produção"],
    themeKeyword: "consistência de creator",
    rationale: "Abertura de semana com tema fácil de identificar e alto potencial de salvamento.",
    isSaved: true,
  },
  {
    slotId: "preview-slot-ter-12",
    dayOfWeek: 2,
    blockStartHour: 12,
    format: "carousel",
    categories: {
      context: ["audience_growth"],
      tone: "didatico",
      proposal: ["framework"],
    },
    status: "drafted",
    expectedMetrics: { viewsP50: 9800, viewsP90: 22100, sharesP50: 188 },
    title: "Framework simples para planejar 5 posts sem ficar sem assunto",
    scriptShort: "Explique os 4 blocos da semana e convide a audiência a copiar a estrutura.",
    themes: ["planejamento semanal", "calendário editorial", "ideias de conteúdo"],
    themeKeyword: "planejamento de posts",
    rationale: "Peça educacional de meio de semana, feita para gerar compartilhamento e salvamento.",
    isSaved: true,
  },
  {
    slotId: "preview-slot-qui-15",
    dayOfWeek: 4,
    blockStartHour: 15,
    format: "reel",
    categories: {
      context: ["sales"],
      tone: "direto",
      proposal: ["case"],
    },
    status: "test",
    isExperiment: true,
    expectedMetrics: { viewsP50: 14600, viewsP90: 33200, sharesP50: 264 },
    title: "Como transformar uma pauta comum em roteiro que atrai publis",
    scriptShort: "Antes e depois do mesmo tema, mostrando como o ângulo certo muda o valor comercial.",
    themes: ["roteiro que vende", "conteúdo comercial", "publis"],
    themeKeyword: "conteúdo que atrai publis",
    rationale: "Slot comercial com ângulo mais direto para testar intenção de compra.",
    isSaved: false,
  },
  {
    slotId: "preview-slot-sex-18",
    dayOfWeek: 5,
    blockStartHour: 18,
    format: "story",
    categories: {
      context: ["community"],
      tone: "proximo",
      proposal: ["checklist"],
    },
    status: "planned",
    expectedMetrics: { viewsP50: 8700, viewsP90: 19300, sharesP50: 121 },
    title: "Checklist de sexta para fechar a semana com posts encaminhados",
    scriptShort: "Sequência curta de stories com check rápido, bastidor e CTA para salvar o board.",
    themes: ["checklist de conteúdo", "organização", "stories estratégicos"],
    themeKeyword: "checklist de sexta",
    rationale: "Fechamento leve de semana para manter constância e preparar o próximo ciclo.",
    isSaved: false,
  },
];

export const PREVIEW_PLANNER_HEATMAP: TimeBlockScoreUI[] = [
  { dayOfWeek: 1, blockStartHour: 9, score: 0.82 },
  { dayOfWeek: 2, blockStartHour: 12, score: 0.74 },
  { dayOfWeek: 3, blockStartHour: 9, score: 0.58 },
  { dayOfWeek: 4, blockStartHour: 15, score: 0.79 },
  { dayOfWeek: 5, blockStartHour: 18, score: 0.69 },
  { dayOfWeek: 6, blockStartHour: 12, score: 0.52 },
];
