import type { CreatorStrategicProfileSynthesis } from "./creatorStrategicProfileSynthesis";
import type { InstagramMetricsSummary } from "./instagramMetricsSummaryService";
import type { NarrativeMapAccessState, NarrativeMapReadingQuotaSnapshot } from "./narrativeMapAccessState";
import type { NarrativeMapMobileReadingItem } from "./narrativeMapMobileViewModel";
import type { LandingCreatorHighlight } from "@/types/landing";
import type { BrandNarrativeMatchResult } from "@/app/lib/brands/brandNarrativeMatchTypes";
import type { MapConfirmationsSnapshot } from "./mapConfirmationsService";
import type { StreamBSignalsSummary } from "./streamBNarrativeSignalsService";
import type { MapEvolutionStatus } from "./mapEvolutionStatusResolver";
import type { ContentIdeaListItem } from "./contentIdeasReadService";
import type { ContentIdeasReadiness } from "./contentIdeasReadinessGate";
import type { AudienceInsights } from "./audienceInsightsService";

export interface DiagnosticoUserInfo {
  name: string | null;
  email?: string | null;
  handle: string | null;
  imageUrl: string | null;
  plan?: string | null;
  /** Canonical mediaKitSlug — drives /mediakit/[slug] navigation. Null when user has no slug yet. */
  mediaKitSlug?: string | null;
  /** True when the user has a verified WhatsApp number linked — enables alert CTA in PautasCard. */
  whatsappLinked?: boolean;
  /**
   * Fase 2 — true quando o perfil do mapa seed está incompleto (campos-chave do
   * creatorProfileExtended ainda não preenchidos). Aciona badge na engrenagem.
   */
  mapProfileIncomplete?: boolean;
  /**
   * Fase 3 — true quando o criador ainda não respondeu o contexto de pricing
   * (creatorProfileExtended.hasDoneSponsoredPosts vazio). Aciona o intro
   * opcional na primeira abertura da Calculadora.
   */
  pricingProfileIncomplete?: boolean;
}

/**
 * Creator's onboarding answers — used to show/edit in the Overview detail view.
 * Matches the shape stored in User.onboardingAnswers.
 */
export interface DiagnosticoOnboardingAnswers {
  whyYouCreate: string | null;
  desiredFeeling: string | null;
  contentLimit: string | null;
  /** Declaração de propósito livre — "para quem cria / o que quer que eles sintam". */
  creatorPurpose: string | null;
}

export interface DiagnosticoCollabSuggestion {
  id: string;
  rank?: number;
  name: string;
  username?: string | null;
  avatarUrl?: string | null;
  /** @deprecated — não exibido no card; mantido para retrocompatibilidade com o path Instagram */
  followers?: number | null;
  mediaKitSlug?: string | null;
  /** @deprecated — substituído por narrativeExample na Fase C */
  avgInteractions?: number | null;
  /** @deprecated — substituído por narrativeExample na Fase C */
  avgReach?: number | null;
  avgShares?: number | null;
  avgSaves?: number | null;
  postCount?: number | null;
  matchedTheme?: boolean;
  matchType?: string | null;
  /**
   * Human-readable explanation of why this creator fits the creator's confirmed map.
   * Generated by the collabs suggestions route using confirmed narrative + territories.
   * Falls back to generic matchType labels in the UI when absent.
   */
  narrativeFitReason?: string | null;
  /**
   * Ponto de encontro: território confirmado do viewer que o criador sugerido
   * também toca. Terreno comum concreto da collab (justificativa narrativa).
   */
  sharedSignal?: string | null;
  /** Territórios do criador sugerido que o viewer não tem — o ângulo novo da collab. */
  distinctSignals?: string[];
  /**
   * Fase C — texto do conteúdo mais narrativamente representativo do criador sugerido.
   * Derivado do título + resumo da leitura com publishIntent="yes" mais recente.
   * Exibido no card como prova de narrativa — não o mais popular, mas o mais representativo.
   */
  narrativeExample?: string | null;
  /**
   * Fase C — label da narrativa central do criador sugerido (ex: "rotina criativa").
   * Usado na razão de fit e como contexto no card.
   */
  suggestedNarrativeLabel?: string | null;
  /**
   * Fase C — território principal do criador sugerido.
   * Derivado do mainNarrative do diagnóstico mais recente.
   */
  suggestedMainTerritory?: string | null;
  /**
   * Fase C — indica que este item veio do path de matching narrativo (não Instagram).
   * Quando true, o card não exibe métricas de audiência.
   */
  narrativeMatch?: boolean;
}

export interface DiagnosticoCollabSuggestionsState {
  /**
   * "upgrade_required" — API returned 403/inactive: user is on free tier.
   * UI shows a soft teaser card inviting upgrade, not a hard block.
   */
  status: "idle" | "loading" | "ready" | "blocked" | "error" | "upgrade_required";
  items: DiagnosticoCollabSuggestion[];
  error?: string | null;
}

export interface DiagnosticoCreatorDirectoryState {
  status: "idle" | "loading" | "ready" | "error";
  creators: LandingCreatorHighlight[];
  error?: string | null;
}

export interface DiagnosticoPageData {
  synthesis: CreatorStrategicProfileSynthesis;
  instagramMetrics: InstagramMetricsSummary | null;
  readings: NarrativeMapMobileReadingItem[];
  /** mainNarrative.label from synthesis — used to enrich reading card contribution labels */
  mainNarrativeLabel: string | null;
  profileSynthesisStatus: string | null;
  accessState: NarrativeMapAccessState;
  readingQuota: NarrativeMapReadingQuotaSnapshot | null;
  instagramConnected: boolean;
  userInfo: DiagnosticoUserInfo;
  /** Brand matches derived from synthesis via brandNarrativeMatcher — empty array when no meaningful signal yet */
  brandMatches: BrandNarrativeMatchResult[];
  /**
   * True when brand matches were derived from the creator's confirmed map
   * (narrative + territories confirmed). When false, matches are synthesis-based.
   * Drives the "Baseado no seu mapa confirmado" badge in DiagnosticoBrandsDetailView.
   */
  brandMapConfirmed: boolean;
  /**
   * Creator's confirmation state for each narrative map dimension.
   * Null when the creator has never confirmed anything — shell defaults all to "pending".
   */
  mapConfirmations: MapConfirmationsSnapshot | null;
  /**
   * True when the creator has never completed the guided onboarding flow.
   * Shell shows MobileOnboardingFlow overlay when true.
   */
  needsOnboarding: boolean;
  /**
   * Stream B (passive Instagram) signal summary.
   * Used by the shell to show "X posts analisados desde sua última visita".
   * Null when not connected or computation failed (non-fatal).
   */
  streamBSignalsSummary: StreamBSignalsSummary | null;
  /**
   * Combined map evolution status — synthesis status capped by creator confirmations.
   * This is what the shell should display; raw synthesis.status is preserved separately.
   */
  mapEvolutionStatus: MapEvolutionStatus;
  /**
   * Pautas (content ideas) already generated for this creator (active + saved).
   * Empty array when the creator hasn't generated any yet.
   */
  contentIdeas: ContentIdeaListItem[];
  /**
   * Whether the map is ready to generate pautas (narrative + territories confirmed).
   * Drives gate UX in the "Pautas" card.
   */
  contentIdeasReadiness: ContentIdeasReadiness;
  /**
   * Creator's onboarding answers — shown + editable in the Diagnóstico Overview detail view.
   * Null when the creator hasn't completed onboarding yet.
   */
  onboardingAnswers?: DiagnosticoOnboardingAnswers | null;
  /**
   * Non-obvious audience recognition insights — what the audience's behavior
   * reveals about the creator that Instagram itself doesn't surface.
   * Null when Instagram is not connected or no confident signal exists.
   */
  audienceInsights?: AudienceInsights | null;
  /**
   * Weekly narrative map summary generated by GPT-4o-mini.
   * A short mirror-language paragraph reflecting what the map revealed this week.
   * Null when not yet generated or feature not enabled.
   */
  weeklyMapSummary?: string | null;
}
