import type { PostCreationAdaptiveIdeaHandoff } from "./postCreationAdaptiveIdeaHandoffState";
import { createPostCreationAdaptiveIdeaHandoffState } from "./postCreationAdaptiveIdeaHandoffState";
import { buildPostCreationAdaptiveAnswerKey } from "./postCreationAdaptiveAnswerKey";
import { buildPostCreationAdaptiveQuiz } from "./postCreationAdaptiveQuizBuilder";
import { detectPostCreationAdaptiveIntent } from "./postCreationAdaptiveRouter";

const baseHandoff: PostCreationAdaptiveIdeaHandoff = {
  decision: {
    contextId: "community",
    proposalId: "humor_scene",
    toneId: "humorous",
    referenceId: "pov",
    intentId: "engajar",
    formatId: "reel",
    durationId: "15-30s",
    narrativeId: "POV",
    dayId: null,
    hourId: null,
    themeId: "pov_rotina",
    pautaId: "adaptive_pov_rotina",
  },
  idea: {
    id: "adaptive_pov_rotina",
    title: "POV sobre rotina",
    description: "Comentários com narrativa POV.",
    lane: "recommended",
    source: "ai_idea",
    confidence: 0.72,
    evidence: ["Objetivo: comentários"],
  },
  blueprint: {
    whatToPost: "POV sobre rotina",
    whyThisPath: "Gera identificação e conversa.",
    whenToPost: "Hoje",
    howItShouldWork: "Abrir com POV, desenvolver contexto e fechar com pergunta.",
    scenes: [
      {
        id: "scene-1",
        title: "Gancho",
        visual: "Creator olhando para câmera",
        message: "POV",
        direction: "Abrir rápido",
        rationale: "Prende atenção",
      },
    ],
  },
};

describe("createPostCreationAdaptiveIdeaHandoffState", () => {
  it("creates nextState in idea stage", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.stage).toBe("idea");
  });

  it("copies decision", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.decision).toBe(baseHandoff.decision);
  });

  it("copies idea", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.idea).toBe(baseHandoff.idea);
  });

  it("keeps blueprint precomputed for the next stage", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.blueprint).toBe(baseHandoff.blueprint);
  });

  it("sets activeDecisionStep to null and blueprintScriptStatus to idle", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.activeDecisionStep).toBeNull();
    expect(result.nextState.blueprintScriptStatus).toBe("idle");
  });

  it("resets scriptId", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.scriptId).toBeNull();
  });

  it("resets linkedContent", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.nextState.linkedContent).toBeNull();
  });

  it("uses handoff decision pautaId as selectedSlotId when present", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.selectedSlotId).toBe("adaptive_pov_rotina");
  });

  it("returns null selectedSlotId when pautaId is empty or null", () => {
    const emptyResult = createPostCreationAdaptiveIdeaHandoffState({
      handoff: {
        ...baseHandoff,
        decision: {
          ...baseHandoff.decision,
          pautaId: "   ",
        },
      },
    });
    const nullResult = createPostCreationAdaptiveIdeaHandoffState({
      handoff: {
        ...baseHandoff,
        decision: {
          ...baseHandoff.decision,
          pautaId: null,
        },
      },
    });

    expect(emptyResult.selectedSlotId).toBeNull();
    expect(nullResult.selectedSlotId).toBeNull();
  });

  it("always returns null selectedScriptId", () => {
    const result = createPostCreationAdaptiveIdeaHandoffState({ handoff: baseHandoff });

    expect(result.selectedScriptId).toBeNull();
  });

  it("works with legacyHandoff generated by buildPostCreationAdaptiveAnswerKey", () => {
    const detection = detectPostCreationAdaptiveIntent("Quero gravar um POV sobre minha família fazendo barulho");
    const questions = buildPostCreationAdaptiveQuiz({ detection });
    const answerKey = buildPostCreationAdaptiveAnswerKey({ detection, questions });

    const result = createPostCreationAdaptiveIdeaHandoffState({
      handoff: answerKey.legacyHandoff,
    });

    expect(result.nextState.stage).toBe("idea");
    expect(result.nextState.decision).toEqual(answerKey.legacyHandoff.decision);
    expect(result.nextState.idea).toEqual(answerKey.legacyHandoff.idea);
    expect(result.nextState.blueprint).toEqual(answerKey.legacyHandoff.blueprint);
    expect(result.selectedSlotId).toBe(answerKey.legacyHandoff.decision.pautaId);
    expect(result.selectedScriptId).toBeNull();
  });
});
