jest.mock("./mobileStrategicProfileAnalysisSubmitClient", () => ({ findPendingVideoAnalysis: jest.fn().mockResolvedValue(null) }));
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MobileStrategicProfileAnalyzeFlow} from '@/app/dashboard/boards/components/videoUpload/appPreview/MobileStrategicProfileAnalyzeFlow';
import {postMobileStrategicProfileAnalysisJson} from '@/app/dashboard/boards/components/videoUpload/appPreview/mobileStrategicProfileAnalysisSubmitClient';
import {validateTemporaryUploadInput} from '@/app/dashboard/boards/videoUpload/videoNarrativeTemporaryUploadValidation';
import {validateVideoNarrativeRealAnalysisPayload} from '@/app/dashboard/boards/videoUpload/videoNarrativeRealAnalysisTypes';
import {validateVideoNarrativeTemporaryUploadCleanupPayload} from '@/app/dashboard/boards/videoUpload/videoNarrativeTemporaryUploadCleanupTypes';
const session={ok:true,status:'signed_upload_session_created',uploadSession:{id:'video-temp-upload-session-audit',uploadUrl:'https://storage.example/video',method:'PUT',headers:{'Content-Type':'video/mp4'},expiresAt:'2099-01-01',retentionTtlMinutes:60,objectKey:'temporary/video-narrative/0123456789abcdef/video-temp-upload-session-audit.mp4'}};
const file=new File(['video'],'video.mp4',{type:'video/mp4'});
afterEach(()=>{cleanup();jest.restoreAllMocks()});
it('preserva a mensagem original sem reiniciar a análise',async()=>{
 const failure=Object.assign(new Error('Falha temporária ao ler o vídeo'),{retryable:true});
 const view=render(<MobileStrategicProfileAnalyzeFlow open onClose={jest.fn()} onComplete={jest.fn()} enableRealAnalysis onSubmitAnalysis={jest.fn().mockRejectedValue(failure)} onCreateUploadSession={jest.fn().mockResolvedValue(session)} onUploadToTemporarySignedUrl={jest.fn().mockResolvedValue({ok:true,status:'uploaded'})} onCleanupTemporaryUpload={jest.fn().mockResolvedValue(undefined)}/>);
 fireEvent.change(view.container.querySelector('input[type="file"]')!,{target:{files:[file]}});
 await waitFor(()=>expect(screen.getByRole('button',{name:'Analisar conteúdo'})).not.toBeDisabled());
 fireEvent.click(screen.getByRole('button',{name:'Analisar conteúdo'}));
 await waitFor(()=>expect(screen.getByText('Falha temporária ao ler o vídeo')).toBeInTheDocument());
 expect(screen.queryByText('Não conseguimos confirmar o envio do vídeo. Volte e envie novamente.')).not.toBeInTheDocument();
});
it('cancelamento durante PUT solicita limpeza mesmo após desmontar',async()=>{
 let finish!:(v:any)=>void;
 const submit=jest.fn().mockResolvedValue({savedDiagnosisId:'audit'}),close=jest.fn(),clean=jest.fn().mockResolvedValue(undefined);
 const view=render(<MobileStrategicProfileAnalyzeFlow open onClose={close} onComplete={jest.fn()} enableRealAnalysis onCleanupTemporaryUpload={clean} onSubmitAnalysis={submit} onCreateUploadSession={jest.fn().mockResolvedValue(session)} onUploadToTemporarySignedUrl={jest.fn().mockReturnValue(new Promise(r=>{finish=r}))}/>);
 fireEvent.change(view.container.querySelector('input[type="file"]')!,{target:{files:[file]}});
 await waitFor(()=>expect(screen.getByRole('button',{name:'Analisar conteúdo'})).not.toBeDisabled());
 fireEvent.click(screen.getByRole('button',{name:'Analisar conteúdo'}));
 await waitFor(()=>expect(finish).toBeDefined());
 const button=screen.getByRole('button',{name:'Fechar fluxo de análise'});expect(button).not.toBeDisabled();fireEvent.click(button);expect(close).toHaveBeenCalled();view.unmount();
 await act(async()=>{finish({ok:true,status:'uploaded'})});
 expect(submit).not.toHaveBeenCalled();expect(clean).toHaveBeenCalled();
});
it('ignora a duração atrasada do arquivo anterior',async()=>{
 jest.useFakeTimers();
 const oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;
 URL.createObjectURL=jest.fn(()=> 'blob:audit');URL.revokeObjectURL=jest.fn();
 const videos:HTMLVideoElement[]=[];
 const create=document.createElement.bind(document);
 jest.spyOn(document,'createElement').mockImplementation(((name:string,options?:any)=>{const element=create(name,options);if(name==='video') videos.push(element as HTMLVideoElement);return element}) as any);
 const sessionFn=jest.fn();
 const view=render(<MobileStrategicProfileAnalyzeFlow open onClose={jest.fn()} onComplete={jest.fn()} onCreateUploadSession={sessionFn}/>);
 const input=view.container.querySelector('input[type="file"]')!;
 fireEvent.change(input,{target:{files:[new File(['a'],'longo.mp4',{type:'video/mp4'})]}});
 fireEvent.change(input,{target:{files:[new File(['b'],'curto.mp4',{type:'video/mp4'})]}});
 Object.defineProperty(videos[3],'duration',{value:10});await act(async()=>{fireEvent.loadedMetadata(videos[3]!)});
 Object.defineProperty(videos[1],'duration',{value:120});await act(async()=>{fireEvent.loadedMetadata(videos[1]!)});
 expect(screen.queryByText(/Este vídeo tem 120s/)).not.toBeInTheDocument();
 expect(screen.getByRole('button',{name:'Analisar conteúdo'})).not.toBeDisabled();
 view.unmount();jest.clearAllTimers();jest.useRealTimers();URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;
});
